name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 'latest'  # Install the latest version of gcloud

      # Step 3: Authenticate with the Google Cloud service account key
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_KEY_FILE }}" > $GITHUB_WORKSPACE/gcloud-key.json
          gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/gcloud-key.json
          gcloud config set project smartopia-462009

      # Step 4: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy shortcut-service \
            --image gcr.io/smartopia-462009/shortcut-service:latest \
            --region asia-east2 \
            --platform managed \
            --allow-unauthenticated
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY_FILE }}
      
      # Optional Step: Post-deployment verification
      - name: Verify Cloud Run Deployment
        run: |
          service_url=$(gcloud run services describe shortcut-service --region asia-east2 --format "value(status.url)")
          echo "Service is live at $service_url"
