name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤 2：设置 Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 'latest'  # 安装最新版本的 gcloud

      # 步骤 3：使用 OAuth2 凭证进行 Google Cloud 身份验证
      - name: Authenticate with Google Cloud using OAuth2
        run: |
          echo "${{ secrets.OAUTH2_CREDENTIALS }}" > $GITHUB_WORKSPACE/oauth2-credentials.json
          gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/oauth2-credentials.json
          gcloud config set project smartopia-462009

      # 步骤 4：部署到 Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy shortcut-service \
            --image gcr.io/smartopia-462009/shortcut-service:latest \
            --region asia-east2 \
            --platform managed \
            --allow-unauthenticated

      # 步骤 5：验证部署（可选）
      - name: Verify Cloud Run Deployment
        run: |
          service_url=$(gcloud run services describe shortcut-service --region asia-east2 --format "value(status.url)")
          echo "Service is live at $service_url"
